type = "card"
title = "Education"

[[items]]
title = "M.S. in Robotics and Intelligent Systems"
subtitle = "Nanyang Technological University"
date = "Aug. 2026 - Jan. 2028 (Expected)"
content = "School of Mechanical and Aerospace Engineering"
image = "/logos/ntu.svg"

[[items]]
title = "B.E. in Internet of Things"
subtitle = "Northeast Agricultural University"
date = "Sep. 2022 - Jun. 2026"
content = "College of Intelligent Science and Engineering"
image = "/logos/neau.png"
