type = "card"
title = "Experience"

[[items]]
title = "Research Attachment"
subtitle = "Singapore Institute of Manufacturing Technology (SIMTech), A*STAR"
date = "08/2026 – Present"
content = "Singapore"
image = "/logos/astar.png"
tags = ["Force-aware Robot Learning", "Robot Manipulation"]

[[items]]
title = "AI Solutions Engineer Intern"
subtitle = "China Unicom Chengdu Branch, Digital Technology Center"
date = "07/2025 – 09/2025"
content = "Chengdu, China"
image = "/logos/china-unicom.png"
tags = ["AI Solution", "IoT Solution"]
