type = "card"
title = "Experience"

[[items]]
title = "A*STAR Research Attachment"
image = "/logos/astar.png"

[[items]]
title = "China Unicom AI Solutions Engineer Intern"
image = "/logos/china-unicom.png"
