type = "card"
title = "Awards"

[[items]]
title = "Silver Medal – Home Credit: Credit Risk Model Stability"
subtitle = "Kaggle Competition Award | Kaggle"
date = "05/2024"
content = "Awarded a silver medal in the Kaggle competition **Home Credit – Credit Risk Model Stability**, ranking in the top 0.5%."
